version: 2
jobs:
  antora:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - run:
          name: Install Antora and its dependencies
          command: |
            yarn global add @antora/cli@2.0
            yarn global add @antora/site-generator-default@2.0
      - run:
          name: Build docs
          command: antora --pull --stacktrace site.yml
      - persist_to_workspace:
          root: gh-pages
          paths:
            - "*"
  site-deploy:
    docker:
      - image: node:lts-jessie
    steps:
      - checkout
      - attach_workspace:
          at: gh-pages
      - run:
          name: Install and configure dependencies
          command: |
            yarn  global add gh-pages@2.0.1
            git config user.email "kamesh.sampath@hotmail.com"
            git config user.name "kameshsampath"
      - add_ssh_keys:
          fingerprints:
            - "c2:dc:84:4b:b7:c2:87:39:80:00:4a:a8:9f:62:44:37"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist gh-pages
workflows:
  version: 2
  build:
    jobs:
      - antora
      - site-deploy:
          requires:
            - antora
          filters:
            branches:
              only: master
