apiVersion: serving.knative.dev/v1alpha1
kind: Configuration
metadata:
  name: greeter
spec:
  revisionTemplate:
    metadata:
      labels:
        app: greeter
    spec:
      container:
        image: quay.io/rhdevelopers/knative-tutorial-greeter:quarkus
        env:
          - name: MESSAGE_PREFIX
            value: Namaste
        livenessProbe:
          httpGet:
            path: /healthz
        readinessProbe:
          httpGet:
            path: /healthz
